#!/usr/bin/env bash

conf_file="$HOME/.dwall.conf"

sequential_wallpapers() {
        local imgs=()
        for item in "$wallpaper_dir"/* ; do
                [[ ! -d "$item" ]] &&\
                        imgs+=( "$item" )
        done

        local index=0
        for((;;)){
                feh "${feh_flags[@]}" "${imgs[index]}"
                ((index++))
                ((index=index%${#imgs[@]}))
		read -rt "$delay" <> <(:) || :
        }
}

randomized_wallpapers() {
        for((;;)){
                feh --randomize "${feh_flags[@]}" "$wallpaper_dir"
                read -rt "$delay" <> <(:) || :
        }
}

main () {
        if [[ ! -f "$conf_file" ]]; then
                echo "wallpaper_dir='~/Pictures'
feh_flags=(--bg-fill)
delay=120" > "$conf_file"
        fi

        source "$conf_file"

        [[ -z "$wallpaper_dir" ]] && exit

        case $1 in
                --sequential|-s)
                        sequential_wallpapers
                ;;
                --random|-r|*)
                        randomized_wallpapers
                ;;

        esac
}

main "$@"
