#!/usr/bin/env bash
# wllppr

set_variables() {
        config_file="$HOME/.wllppr.conf"
        files=()
        used_files=()
        file_count=0
}

get_files() {
        file_count=0
        # count the number of files
        for item in "$pic_dir"/*; do
                # if not a directory
                [[ ! -d $item && "$item" != *"README.md" ]] && {
                        # add to file list
                        files+=("$item")
                        ((file_count++))
                }
        done
}

get_config() {
        # create a default config if
        # config doesnt exist
        [[ ! -a $config_file ]] && {
                echo "pic_dir=$(xdg-user-dir PICTURES)" > "$config_file"
        }

        source "$config_file"
}

interrupt() {
        local num file
        for((;;)) {
                # get a random file nummber
                num="$(( RANDOM % file_count ))"
                
                file="${files[$num]}"
                [[ "${files[*]}" == *$file* &&\
                   "${used_files[*]}" != *$file* ]] && {
                                used_files+=( "$file" )
                                (( ${#files[@]} == ${#used_files[@]} )) && {
                                        used_files=()
                                }
                                wal -qi "$file"
                                break
                }
        }
}

reload() {
        set_variables
        get_config
        get_files
}

main() {
        trap 'interrupt' SIGUSR1
        trap 'reload'    SIGUSR2

        set_variables
        get_config
        get_files


        while :; do
                read -rt 9999 <> <(:) || :
        done
}

main "$@"