#!/usr/bin/env bash
#
# wllppr

download_img() {
    # base url
    base_url="https://source.unsplash.com"

    # user stuff
    url="${base_url}${WLLPPR_USER:+/user/$WLLPPR_USER${WLLPPR_LIKED:+/likes}}"

    # featured pics
    url="${url}${WLLPPR_FEATURED:+/featured}"

    # image dimension
    url="${url}${WLLPPR_DIMENSION:+/${WLLPPR_DIMENSION}}"

    # search tags
    url="${url}${WLLPPR_SEARCH_TAGS:+/?${WLLPPR_SEARCH_TAGS}}"

    [[ $url == $base_url ]] && url="${url}/random"

    curl -L "$url" > download.jpeg || {
        printf '%s\n' "error: could not download the image" >&2
        exit 1
    }
}

main() {

    # create cache dir
    mkdir -p "${XDG_CACHE_HOME:=${HOME}/.cache}/wllppr"

    cd -- "${XDG_CACHE_HOME:=${HOME}/.cache}/wllppr/" || {
        printf '%s\n' "error: Unable to open cache folder" >&2
        exit 1
    }

    download_img

    wal -i ./download.jpeg &
}

main "$@"